spring.application.name=hospitalManagement

#MYSQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/hospitalmanagement
spring.datasource.username=root
spring.datasource.password=vishal

#JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA/Hibernate Setting (Optional but recommed)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#debug=true

#used for Data migration
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
